### ISSUE TITLE
Which version of python 3.9 is specific

### ISSUE THREAD

**Issue by CodeYYCleer** [J2on/PointCloudToMesh_Open3D#1]
hi，which version of python 3.9 is specific

**Comment by CodeYYCleer** [comment]
i ve used 3.9.0 and 3.9.10 ，both method failed，this is the traceback，help ，please
Traceback (most recent call last):
  File "D:\Tools\PyCharm 2023.3.3\plugins\python\helpers\pydev\pydevd.py", line 1534, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Tools\PyCharm 2023.3.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\Project\2024\python\pcdtoobj\cpdtoobj.py", line 29, in <module>
    poisson_mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_poisson(pcd, depth=8, width=0, scale=1.1, linear_fit=False)[0]
RuntimeError: [Open3D Error] (class std::tuple<class std::shared_ptr<class open3d::geometry::TriangleMesh>,class std::vector<double,class std::allocator<double> > > __cdecl open3d::geometry::TriangleMesh::CreateFromPointCloudPoisson(const class open3d::geometry::PointCloud &,unsigned __int64,float,float,bool,int)) D:\a\Open3D\Open3D\cpp\open3d\geometry\SurfaceReconstructionPoisson.cpp:732: Point cloud has no normals

**Comment by J2on** [comment]
Hi

It seems like there are no normals in the pcd file, as indicated by the
error message 'Point cloud has no normals.'

Have you check about this?

**Comment by J2on** [comment]
Unfortunately, I can't check the exact Python version now because I changed my laptop

**Comment by CodeYYCleer** [comment]
thanks, resolved，i ve use an error cpd  - -！
